services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      CONFIG_PATH: /app/config.yaml
      DB_PATH: /app/data/vkusvill.db
    volumes:
      - ./:/app
      - ./data/vkusvill.db:/app/data/vkusvill.db
    working_dir: /app
    command:
      [
        "watchfiles",
        "--filter",
        "python",
        "--target-type",
        "command",
        "python -m vkusvillbot.main",
        "/app",
      ]
