name: Deploy to macmini

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-macmini
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, macmini, vkusvillbot]
    steps:
      - name: Deploy
        run: /Users/macmini/dev-server/vkusvillbot/scripts/deploy_macmini.sh
